# Generated by Django 6.0 on 2025-12-27 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('is_scrapped', models.BooleanField(default=False)),
                ('default_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipments', to=settings.AUTH_USER_MODEL)),
                ('maintenance_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='teams.maintenanceteam')),
            ],
        ),
    ]
